In [ ]:
import torch
print(torch.__version__)
import math

2.11.0+cpu


In [ ]:
z=torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
i=torch.ones(5,3)
print(i)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
torch.manual_seed(1749)
r1=torch.rand(2,2)
print("a random tensor r1")
print(r1)

r2=torch.rand(3,3)
print("a random tensor r2")
print(r2)

torch.manual_seed(1749)
r3=torch.rand(2,2)
print(r3)
r4=torch.rand(3,3)
print(r4)

a random tensor r1
tensor([[0.3170, 0.5503],
        [0.4404, 0.4423]])
a random tensor r2
tensor([[0.0892, 0.4907, 0.9173],
        [0.9434, 0.2533, 0.4133],
        [0.3578, 0.8868, 0.5795]])
tensor([[0.3170, 0.5503],
        [0.4404, 0.4423]])
tensor([[0.0892, 0.4907, 0.9173],
        [0.9434, 0.2533, 0.4133],
        [0.3578, 0.8868, 0.5795]])


In [ ]:
ones=torch.ones(2,3)
print(ones)
twos=torch.ones(2,3)*2
print(twos)
threes=ones+twos
print(threes)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])


In [ ]:
r=torch.rand(2,2)-0.5*2
print(" \n a random matrix ")
print(r)

print(" \n absolute value of r ")
print(torch.abs(r))

print(" \n inverse sine of r ")
print(torch.asin(r))

print(" \n det of r ")
print(torch.det(r))

print(" \n standard deviation and average of r ")
print(torch.std_mean(r))

print(" \n max value of r ")
print(torch.max(r))

 
 a random matrix 
tensor([[-0.0384, -0.4036],
        [-0.6719, -0.6659]])
 
 absolute value of r 
tensor([[0.0384, 0.4036],
        [0.6719, 0.6659]])
 
 inverse sine of r 
tensor([[-0.0384, -0.4154],
        [-0.7368, -0.7287]])
 
 det of r 
tensor(-0.2456)
 
 standard deviation and average of r 
(tensor(0.2985), tensor(-0.4450))
 
 max value of r 
tensor(-0.0384)


In [ ]:
x=torch.empty(2,3)
print(x.dtype)
print(x)

torch.float32
tensor([[7.2599e-29, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
zeros=torch.zeros(2,3)
print(zeros)
print(zeros.dtype)
ones=torch.ones(2,3)
print(ones)
print(ones.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [ ]:
torch.manual_seed(1729)
random=torch.rand(3,3)
print(random)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691],
        [0.2332, 0.4047, 0.2162]])


In [ ]:
torch.manual_seed(1729)
random=torch.rand(3,3)
rando=torch.rand(3,3)
print(random)
print(rando)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691],
        [0.2332, 0.4047, 0.2162]])
tensor([[0.9927, 0.4128, 0.5938],
        [0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])


In [ ]:
x=torch.empty(2,2,3)
print(x)
print(x.shape)

zeros_like_x=torch.zeros_like(x)
print(zeros_like_x)
print(zeros_like_x.shape)

ones_like_x=torch.ones_like(x)
print(ones_like_x)
print(ones_like_x.shape)

empty_like_x=torch.empty_like(x)
print(empty_like_x)
print(empty_like_x.shape)

rand_like_x=torch.rand_like(x)
print(rand_like_x)
print(rand_like_x.shape)

tensor([[[2.0949e-26, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0000e+00, 1.0000e+00]],

        [[1.0000e+00, 1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[2.1070e-26, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0000e+00, 1.0000e+00]],

        [[1.0000e+00, 1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]],

        [[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]]])
torch.Size([2, 2, 3])


In [ ]:
some_constants=torch.tensor([[3.1417,2.7134],[0.0987,5.4213]])
print(some_constants)

some_integers=torch.tensor((2,3,5,6,9,3,6,6,0))
print(some_integers)

more_integers=torch.tensor(((2,3,4), [9,0,6]))
print(more_integers)

tensor([[3.1417, 2.7134],
        [0.0987, 5.4213]])
tensor([2, 3, 5, 6, 9, 3, 6, 6, 0])
tensor([[2, 3, 4],
        [9, 0, 6]])


In [ ]:
ones=torch.ones(2,2)
twos=torch.ones(2,2)*2
threes=(torch.ones(2,2)*7-1)/2
fours=twos**2
print(ones)
print(twos)
print(threes)
print(fours)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])


In [ ]:
powers2=twos**torch.tensor(([1,2],[3,4]))
print(powers2)
fives=ones+fours
print(fives)
dozens=threes*fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [ ]:
a=torch.rand(2,3)
b=torch.rand(3,3)
print(a)
print(b)
print(a*b)

tensor([[0.2941, 0.3788, 0.4567],
        [0.0649, 0.6677, 0.7826]])
tensor([[0.1332, 0.0023, 0.4945],
        [0.3857, 0.9883, 0.4762],
        [0.7242, 0.0776, 0.4004]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [ ]:
rand=torch.rand(2,4)
doubled=rand*(torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.6923, 0.7545, 0.7746, 0.2330],
        [0.8441, 0.9004, 0.3995, 0.6324]])
tensor([[1.3846, 1.5091, 1.5491, 0.4660],
        [1.6881, 1.8008, 0.7990, 1.2648]])


In [ ]:
a=torch.rand(2,3,2)
print(a)
doubled=a*(torch.ones(  3,2)*2)
print(doubled)

tensor([[[0.4460, 0.9289],
         [0.6293, 0.6264],
         [0.4704, 0.6077]],

        [[0.4757, 0.5874],
         [0.4363, 0.6339],
         [0.3208, 0.4323]]])
tensor([[[0.8920, 1.8577],
         [1.2585, 1.2528],
         [0.9407, 1.2153]],

        [[0.9515, 1.1747],
         [0.8727, 1.2679],
         [0.6415, 0.8646]]])


In [ ]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

Common functions:
tensor([[-0.4695,  0.4657, -0.5747, -0.1185],
        [-0.2246,  0.2155, -0.5310,  0.4235]])
tensor([[0.4695, 0.4657, 0.5747, 0.1185],
        [0.2246, 0.2155, 0.5310, 0.4235]])
tensor([[-0., 1., -0., -0.],
        [-0., 1., -0., 1.]])
tensor([[-1.,  0., -1., -1.],
        [-1.,  0., -1.,  0.]])
tensor([[-0.4695,  0.4657, -0.5000, -0.1185],
        [-0.2246,  0.2155, -0.5000,  0.4235]])


ALTERING TENSORS IN PLACE

In [ ]:
a=torch.tensor([0,math.pi/4,math.pi/2,(3*math.pi)/4])
print(a)
print(torch.sin(a))
print(a)

b=torch.tensor([0,math.pi/4,math.pi/2,(3*math.pi)/4])
print("\nb:")
print(b)
print(torch.sin_(b))
print(b)

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a=torch.ones(2,2)
b=torch.rand(2,2)
print(a)
print(b)
print("\n after adding:")
print(a.add_(b))
print(a)
print(b)
print("\n after multiplying:")
print(b.mul_(b))
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.2301, 0.9151],
        [0.5056, 0.2659]])

 after adding:
tensor([[1.2301, 1.9151],
        [1.5056, 1.2659]])
tensor([[1.2301, 1.9151],
        [1.5056, 1.2659]])
tensor([[0.2301, 0.9151],
        [0.5056, 0.2659]])

 after multiplying:
tensor([[0.0530, 0.8375],
        [0.2557, 0.0707]])
tensor([[1.2301, 1.9151],
        [1.5056, 1.2659]])
tensor([[0.0530, 0.8375],
        [0.2557, 0.0707]])


In [ ]:
a=torch.ones(2,2)
b=a
print(a)
print(b)
a[0][1]=560
print(a)
print(b)
a=a*5050
print(a)
print(b)
a[0][1]=56
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[  1., 560.],
        [  1.,   1.]])
tensor([[  1., 560.],
        [  1.,   1.]])
tensor([[   5050., 2828000.],
        [   5050.,    5050.]])
tensor([[  1., 560.],
        [  1.,   1.]])
tensor([[5050.,   56.],
        [5050., 5050.]])
tensor([[  1., 560.],
        [  1.,   1.]])


In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
print(a)
print(a.shape)
print(b.shape)

tensor([[[0.2546, 0.9369, 0.7488,  ..., 0.6644, 0.5120, 0.8736],
         [0.7780, 0.7681, 0.2989,  ..., 0.5191, 0.1921, 0.8108],
         [0.1085, 0.7236, 0.2208,  ..., 0.6087, 0.1352, 0.3083],
         ...,
         [0.1105, 0.4508, 0.4639,  ..., 0.3002, 0.5353, 0.1164],
         [0.1970, 0.4144, 0.9641,  ..., 0.3223, 0.9784, 0.3546],
         [0.9322, 0.9665, 0.5321,  ..., 0.8324, 0.9531, 0.1881]],

        [[0.8000, 0.4898, 0.5590,  ..., 0.1362, 0.8462, 0.0297],
         [0.3421, 0.1267, 0.7821,  ..., 0.8282, 0.1016, 0.5877],
         [0.5486, 0.9306, 0.7979,  ..., 0.0474, 0.1172, 0.0395],
         ...,
         [0.9317, 0.2094, 0.8330,  ..., 0.4250, 0.6667, 0.3339],
         [0.0975, 0.4867, 0.6959,  ..., 0.9412, 0.9771, 0.7540],
         [0.4325, 0.6751, 0.3974,  ..., 0.4711, 0.3823, 0.1096]],

        [[0.5966, 0.8581, 0.7814,  ..., 0.1991, 0.7730, 0.6502],
         [0.4582, 0.1661, 0.1435,  ..., 0.1118, 0.3229, 0.2236],
         [0.8601, 0.5960, 0.3052,  ..., 0.7770, 0.7630, 0.

In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.9211, 0.6042, 0.7966, 0.6166, 0.6064, 0.9906, 0.0350, 0.0411, 0.7051,
         0.5522, 0.2367, 0.5497, 0.1662, 0.2961, 0.9811, 0.6110, 0.1597, 0.4791,
         0.5845, 0.8477]])
torch.Size([20])
tensor([0.9211, 0.6042, 0.7966, 0.6166, 0.6064, 0.9906, 0.0350, 0.0411, 0.7051,
        0.5522, 0.2367, 0.5497, 0.1662, 0.2961, 0.9811, 0.6110, 0.1597, 0.4791,
        0.5845, 0.8477])
torch.Size([2, 2])
torch.Size([2, 2])
