In [ ]:
# import torch
# import math

In [ ]:
x=torch.tensor(4.0,requires_grad=True)

In [ ]:
# y=x**2

In [ ]:
z=torch.cos(y)

In [ ]:
# x

tensor(4., requires_grad=True)

In [ ]:
# y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
# z

tensor(-0.9577, grad_fn=<CosBackward0>)

In [ ]:
z.backward()

In [ ]:
# x.grad

tensor(2.3032)

CODING WRT A NN

In [ ]:
import torch
import math
x=torch.tensor(6.7)
y=torch.tensor(0.0)
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [ ]:
def binary_cross_entropy_loss(prediction,target):
  epsilon=1e-8
  prediction=torch.clamp(prediction,epsilon,1-epsilon)
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [ ]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss=binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)

tensor(6.6918)


In [ ]:
b.grad

tensor(0.9988)

In [ ]:
a=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [ ]:
a

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
b=(a**2).mean()


In [ ]:
b

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
b.backward()

In [ ]:
a.grad

tensor([2., 4., 6.])

In [ ]:
a.grad.zero_()

tensor([0., 0., 0.])

In [ ]:
a.requires_grad_(False)

tensor([1., 2., 3.])

In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
b

tensor(4.6667, grad_fn=<MeanBackward0>)